#!/usr/bin/env python3

def SymbolToNumber(symbol):

    if symbol == "A":
        return 0
    elif symbol == "C":
        return 1
    elif symbol == "G":
        return 2
    elif symbol == "U":
        return 3


def PatternToNumber(Pattern):

    if Pattern == "":
        return 0

    symbol = Pattern[len(Pattern)-1]
    prefix = Pattern[0:len(Pattern)-1]
    return 4*PatternToNumber(prefix) + SymbolToNumber(symbol)


def RNAtoAminoAcid(Pattern):

    Amino = 'KNKNTTTTRSRSIIMIQHQHPPPPRRRRLLLLEDEDAAAAGGGGVVVV*Y*YSSSS*CWCLFLF'
    out = ""

    for i in range (0, len(Pattern) - 3 + 1, 3):

        amino_index = PatternToNumber(Pattern[i:i+3])
        amino_acid = Amino[amino_index]
        if amino_acid != '*':
            out += amino_acid

    return out
    

with open("rosalind_ba4a.txt") as file:
    line = file.readline()
print(RNAtoAminoAcid(line.strip("\n")))
