#!/usr/bin/env python3

def count(Text, Pattern):
    counter = 0
    for i in range (0, len(Text) - len(Pattern) + 1):
        if (Text[i : i + len(Pattern)] == Pattern):
            counter = counter + 1
    return counter

with open("rosalind_ba1a.txt") as file:
    lines = file.readlines()
print (count(lines[0].strip("\n"),lines[1].strip("\n")))
