#!/usr/bin/env python3

def Positions(Pattern, Genome):

    positions = ""

    for i in range(0,len(Genome) - len(Pattern) + 1):
        if Genome[i : i + len(Pattern)] == Pattern:
            positions += str(i) + " "

    return positions


with open("rosalind_ba1d.txt") as file:
    lines = file.readlines()
print (Positions(lines[0].strip("\n"),lines[1].strip("\n")))
