#!/usr/bin/env python3

def HammingDistance(p,q):
    n = len(p)
    counter = 0
    for i in range(0,n):
        if p[i] != q[i]:
            counter += 1
    return counter

with open("rosalind_ba1g.txt") as file:
    lines = file.readlines()
print(HammingDistance(lines[0].strip("\n"), lines[1].strip("\n")))
