#!/usr/bin/env python3

def Row(char):

    if char == 'A':
        return 0
    if char == 'C':
        return 1
    if char == 'G':
        return 2
    if char == 'T':
        return 3


def Probability(kmer, Profile):

    prob = 1
    for i in range(0,len(kmer)):

        char = kmer[i]
        row = Row(char)
        prob *= Profile[row][i]

    return prob


def ProfileMostProbable_kMer(Text, k, Profile):

    maximum = Probability(Text[0:k],Profile)
    most_probable = Text[0:k]
    
    for i in range(1,len(Text) - k + 1):

        if (Probability(Text[i:i+k],Profile) > maximum):

            maximum = Probability(Text[i:i+k],Profile)
            most_probable = Text[i:i+k]

    return most_probable


def MaxNmbrOfOccurencesOfLetterInColumn(Motifs,j):

    countACGT = [0,0,0,0]
    for i in range(0,len(Motifs)):

        if(Motifs[i][j] == 'A'):
            countACGT[0] +=1
        elif(Motifs[i][j] == 'C'):
            countACGT[1] +=1
        elif(Motifs[i][j] == 'G'):
            countACGT[2] +=1
        elif(Motifs[i][j] == 'T'):
            countACGT[3] +=1

    return max(countACGT)


def Score(Motifs):

    score = 0;
    for i in range(0,len(Motifs[0])):

        score += (len(Motifs) - MaxNmbrOfOccurencesOfLetterInColumn(Motifs,i))

    return score


def FormProfileWithPseudocounts(strings):

    n = len(strings)
    k = len(strings[0])

    Profile = []

    for m in range (0,4):
        
        ProfileRow = [1]*k
        for i in range(0,k):
            for j in range(0,n):
                row = Row(strings[j][i])
                if m == row:
                    ProfileRow[i] += 1
                    
            ProfileRow[i] = ProfileRow[i]/(n + 4)
                    
        Profile.append(ProfileRow)

    return Profile


def GreedyMotifSearch(k,t,Dna):

    BestMotifs = []
    
    for i in range(0,len(Dna)):
        BestMotifs.append(Dna[i][0:k])

    for i in range(0, len(Dna[0]) - k + 1):

        Motifs = []
        Motif1 = Dna[0][i:i+k]
        Motifs.append(Motif1)
        
        for j in range(1,t):

            Profile = FormProfileWithPseudocounts(Motifs)
            Motif_j = ProfileMostProbable_kMer(Dna[j], k, Profile)

            Motifs.append(Motif_j)

        if (Score(Motifs) < Score(BestMotifs)):
            BestMotifs = Motifs

    return BestMotifs



def Output(array):

    print ('\n'.join(array))



with open("rosalind_ba2e.txt") as file:
    lines = file.readlines()

k = int(lines[0].strip('\n').split(' ')[0])
t = int(lines[0].strip('\n').split(' ')[1])
Dna = []

for i in range(1,len(lines)):
    Dna.append(lines[i].strip('\n'))

Output(GreedyMotifSearch(k,t,Dna))
