#!/usr/bin/env python3

def MinNumCoins(money,coins):

    minNumCoins = [0]

    for m in range(1, money + 1):

        minNumCoins.append(m/min(coins) + 1) # this is the maximum possible number of coins
        
        for i in range(0,len(coins)):
            if (m - coins[i] >= 0):
                if (minNumCoins[m - coins[i]] + 1 < minNumCoins[m]):

                    minNumCoins[m] = minNumCoins[m - coins[i]] + 1

    return minNumCoins[money]
                       

with open("rosalind_ba5a.txt") as file:
    lines = file.readlines()

money = int(lines[0].strip('\n'))
coins_str = lines[1].strip('\n').split(',')
coins = []

for coin in coins_str:
    coins.append(int(coin))

print(MinNumCoins(money,coins))
