#!/usr/bin/env python3

def StringFromGenomePath(sequence):

    string = sequence[0] #selecting the whole first sample of sequence
    for i in range(1,len(sequence)):
        #adding only the last symbol of each sample in sequence, starting from the second
        string += sequence[i][len(sequence[i])-1]

    return string


with open("rosalind_ba3b.txt") as file:
    lines = file.readlines()
    
for i in range (0,len(lines)):
    lines[i] = lines[i].strip("\n")
    
print(StringFromGenomePath(lines))
