#!/usr/bin/env python3

def OverlapGraph(Patterns):

    overlaps = ""
    prefixes = {}
    k = len(Patterns[0]) # length of k-mer

    # sorting k-mers by their prefixes
    for i in range(0,len(Patterns)):
                   
        # key: prefix, value: array of k-mers with the corresponding prefix
        if (Patterns[i][0:k-1] not in prefixes.keys()):
            prefixes[Patterns[i][0:k-1]] = [Patterns[i]]
        else:
            prefixes[Patterns[i][0:k-1]].append(Patterns[i])


    # checking if any sufixes match any prefixes
    for i in range(0,len(Patterns)):

        if (Patterns[i][1:k] in prefixes.keys()):
            for kmer in prefixes[Patterns[i][1:k]]:
                overlaps += Patterns[i] + " -> " + kmer + "\n"

    return overlaps


with open("rosalind_ba3c.txt") as file:
    lines = file.readlines()
    
for i in range (0,len(lines)):
    lines[i] = lines[i].strip("\n")
    
print(OverlapGraph(lines))
